---
apiVersion: v1
kind: Pod
metadata:
  name: tackle-hub
  labels:
    app: tackle-hub
spec:
  containers:
  - name: main
    image: quay.io/jortel/tackle-hub:latest
  restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: tackle-hub
spec:
  selector:
    app: tackle-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Route
metadata:
  name: tackle-hub
spec:
  host: konveyor-tackle-hub.apps.cluster-jortel.v2v.bos.redhat.com
  to:
    kind: Service
    name: tackle-hub
  wildcardPolicy: None

