---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tackle-hub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tackle-hub
  labels:
    app: tackle-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tackle-hub
  template:
    metadata:
      labels:
        app: tackle-hub
    spec:
      serviceAccountName: tackle-hub
      automountServiceAccountToken: true
      containers:
      - name: main
        image: quay.io/jortel/tackle-hub:latest
        env:
          - name: "HUB_BASE_URL"
            value: "http://tackle-hub.tackle-operator.svc.cluster.local"
          - name: "SECRET_PATH"
            value: "/var/run/secrets/konveyor.io/tackle/addon.json"
          - name: "ARTIFACT_ROOT_PATH"
            value: "/var/run/tackle/artifact"
        volumeMounts:
          - name: artifact
            mountPath: /var/run/tackle/artifact
      volumes:
        - name: artifact
          persistentVolumeClaim:
            claimName: tackle-hub

---
apiVersion: v1
kind: Service
metadata:
  name: tackle-hub
spec:
  selector:
    app: tackle-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Route
metadata:
  name: tackle-hub
spec:
  host: konveyor-tackle-hub.apps.cluster-jortel.v2v.bos.redhat.com
  to:
    kind: Service
    name: tackle-hub
  wildcardPolicy: None

